import NextHead from 'next/head';
import { FC } from 'react';

type HeadProp = {
  title?: string;
  description?: string;
  icon?: string;
};

const Head: FC<HeadProp> = ({
  title = 'Gamio FE Challenge',
  description = 'Generated by create next app',
  icon = '/favicon.ico',
}) => (
  <NextHead>
    <title>{title}</title>
    <meta name="description" content={description} />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href={icon} />
  </NextHead>
);
export default Head;
