import { Container, Text } from '@mantine/core';
import { NextPage } from 'next';
import Head from 'next/head';

const Settings: NextPage = () => (
  <>
    <Head>
      <title>Gamio FE Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Container mb={36} py={5} size="xl">
      <Text fz={24} fw={900} lh="30px" transform="uppercase">
        Settings
      </Text>
    </Container>
  </>
);
export default Settings;
