import { Container, Text, SimpleGrid } from '@mantine/core';
import { NextPage } from 'next';
import Head from 'next/head';

import { Card } from '@/components/Card';
import { CardType } from '@/components/Card/type';

const data = [1, 2, 3, 4];

const Inventory: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gamio FE Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container mb={36} py={5} size="xl">
        <Text fz={24} fw={900} lh="30px" transform="uppercase">
          Overview
        </Text>
      </Container>

      <Container size="xl">
        <SimpleGrid
          cols={4}
          spacing={36}
          breakpoints={[
            { maxWidth: 'lg', cols: 3, spacing: 'lg' },
            { maxWidth: 'md', cols: 2, spacing: 'md' },
            { maxWidth: 'xs', cols: 1, spacing: 'xs' },
          ]}
          sx={{ justifyItems: 'center' }}
        >
          {data.map((item) => (
            <Card
              key={item}
              cardType={CardType.Claimed}
              title="Tralalalala balallalaal affafafafa"
              imageUrl="https://picsum.photos/200/300"
            />
          ))}
        </SimpleGrid>
      </Container>
    </>
  );
};
export default Inventory;
